# Назва вашого сайту
title: rent-car

# Опис сайту
description: Welcome to rent car app.

# URL базової адреси вашого сайту на GitHub Pages
baseurl: "/"

# Параметри GitHub Pages
remote_theme: jekyll/minimal-mistakes # Тема вашого сайту (можете вибрати іншу тему)
